version: 2

before:
  hooks:
    - go mod tidy
    
builds:
  - id: cli
    binary: ssh-ca-client-cli
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    main: ./cmd/ssh-ca-client-cli
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
  - id: windowscli
    binary: ssh-ca-client-cli
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - windows
    main: ./cmd/ssh-ca-client-cli
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
  - id: windowsgui
    binary: ssh-ca-client
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - windows
    hooks:
      pre:
        - go install github.com/tc-hib/go-winres@v0.3.3
        - go generate ./cmd/ssh-ca-client/generate_windows.go
    main: ./cmd/ssh-ca-client
    ldflags:
      - -H=windowsgui -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: gui
    binary: ssh-ca-client
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
    main: ./cmd/ssh-ca-client
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

archives:
  - allow_different_binary_count: true
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - config-example.yml
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  make_latest: true
  replace_existing_artifacts: true
  prerelease: auto
  make_latest: true

nfpms:
  - ids:
      - cli
      - gui
    maintainer: Andrew Heberle <andrew.heberle@gmail.com>
    formats:
      - deb
    contents:
      - src: systemd/
        dst: /usr/lib/systemd/system

sboms:
  - id: package
    artifacts: package
    disable: false
  - artifacts: archive
    disable: false