// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package model

import (
	"time"
)

const (
	OidcAuthScopes = "oidcAuth.Scopes"
)

// Defines values for GetRevocationListEndpointParamsCertificateType.
const (
	GetRevocationListEndpointParamsCertificateTypeHost GetRevocationListEndpointParamsCertificateType = "host"
	GetRevocationListEndpointParamsCertificateTypeUser GetRevocationListEndpointParamsCertificateType = "user"
)

// Valid indicates whether the value is a known member of the GetRevocationListEndpointParamsCertificateType enum.
func (e GetRevocationListEndpointParamsCertificateType) Valid() bool {
	switch e {
	case GetRevocationListEndpointParamsCertificateTypeHost:
		return true
	case GetRevocationListEndpointParamsCertificateTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for PostRevokeCertificateEndpointParamsCertificateType.
const (
	PostRevokeCertificateEndpointParamsCertificateTypeHost PostRevokeCertificateEndpointParamsCertificateType = "host"
	PostRevokeCertificateEndpointParamsCertificateTypeUser PostRevokeCertificateEndpointParamsCertificateType = "user"
)

// Valid indicates whether the value is a known member of the PostRevokeCertificateEndpointParamsCertificateType enum.
func (e PostRevokeCertificateEndpointParamsCertificateType) Valid() bool {
	switch e {
	case PostRevokeCertificateEndpointParamsCertificateTypeHost:
		return true
	case PostRevokeCertificateEndpointParamsCertificateTypeUser:
		return true
	default:
		return false
	}
}

// CertificateResponse defines model for Certificate Response.
type CertificateResponse struct {
	// Certificate Issued Certificate
	Certificate []byte `json:"certificate"`
}

// CertificateRevocation defines model for Certificate Revocation.
type CertificateRevocation struct {
	// Proof Proof of possession comprising of ${timestamp}.${fingerprint}.${signature}
	Proof string `json:"proof"`

	// PublicKey SSH public key to sign
	PublicKey []byte `json:"public_key"`

	// Serial Serial number of certificate to revoke
	Serial string `json:"serial"`
}

// HostCertificateRenew defines model for Host Certificate Renew.
type HostCertificateRenew struct {
	// Certificate SSH certificate to renew
	Certificate []byte `json:"certificate"`

	// Lifetime Lifetime of renewed Host SSH certificate
	Lifetime *int `json:"lifetime,omitempty"`

	// Proof Proof of possession comprising of ${timestamp}.${fingerprint}.${signature}
	Proof string `json:"proof"`

	// PublicKey SSH public key to sign
	PublicKey []byte `json:"public_key"`
}

// HostCertificateRequest defines model for Host Certificate Request.
type HostCertificateRequest struct {
	// Identity Identity Token JWT from OIDC IdP
	Identity string `json:"identity"`

	// Lifetime Lifetime of issued Host SSH certificate
	Lifetime *int `json:"lifetime,omitempty"`

	// Principals List of principals to include on the issued certificate
	Principals []string `json:"principals"`

	// Proof Proof of possession comprising of ${timestamp}.${fingerprint}.${signature}
	Proof string `json:"proof"`

	// PublicKey SSH public key to sign
	PublicKey []byte `json:"public_key"`
}

// KeyRevocationListResponse defines model for Key Revocation List Response.
type KeyRevocationListResponse struct {
	// Krl Key Revocation List
	Krl       []byte `json:"krl"`
	Signature string `json:"signature"`
}

// RevocationResponse defines model for Revocation Response.
type RevocationResponse struct {
	RevokedAt time.Time `json:"revoked_at"`
}

// UserCertificateRequest defines model for User Certificate Request.
type UserCertificateRequest struct {
	// Extensions Extensions to include in the issued SSH certificate
	Extensions *[]string `json:"extensions,omitempty"`

	// Identity Identity Token JWT from OIDC IdP
	Identity string `json:"identity"`

	// Lifetime Lifetime of issued SSH certificate
	Lifetime *int `json:"lifetime,omitempty"`

	// Proof Proof of possession comprising of ${timestamp}.${fingerprint}.${signature}
	Proof string `json:"proof"`

	// PublicKey SSH public key to sign
	PublicKey []byte `json:"public_key"`
}

// PostCertificateRequestEndpointV2JSONBody defines parameters for PostCertificateRequestEndpointV2.
type PostCertificateRequestEndpointV2JSONBody struct {
	// Extensions Extensions to include in issued SSH certificate in seconds
	Extensions *[]string `json:"extensions,omitempty"`

	// Identity Identity Token JWT from OIDC IdP
	Identity string `json:"identity"`

	// Lifetime Lifetime of issued SSH certificate
	Lifetime *float32 `json:"lifetime,omitempty"`

	// Nonce Proof of possession comprising of ${timestamp}.${fingerprint}.${format}:${signature}
	Nonce string `json:"nonce"`

	// PublicKey SSH public key to sign
	PublicKey string `json:"public_key"`
}

// PostCertificateRequestEndpointV2Params defines parameters for PostCertificateRequestEndpointV2.
type PostCertificateRequestEndpointV2Params struct {
	// Authorization Access Token JWT from OIDC IdP
	Authorization string `json:"Authorization"`
}

// PostHostCertificateRenewEndpointV2JSONBody defines parameters for PostHostCertificateRenewEndpointV2.
type PostHostCertificateRenewEndpointV2JSONBody struct {
	// Certificate SSH certificate to renew
	Certificate string `json:"certificate"`

	// Lifetime Lifetime of renewed Host SSH certificate
	Lifetime *float32 `json:"lifetime,omitempty"`

	// Nonce Proof of possession comprising of ${timestamp}.${keyfingerprint}.${format}:${signature}
	Nonce string `json:"nonce"`

	// PublicKey SSH public key of certificate to be renewed
	PublicKey string `json:"public_key"`
}

// PostHostCertificateRequestEndpointV2JSONBody defines parameters for PostHostCertificateRequestEndpointV2.
type PostHostCertificateRequestEndpointV2JSONBody struct {
	// Lifetime Lifetime of issued Host SSH certificate
	Lifetime *float32 `json:"lifetime,omitempty"`

	// Nonce Proof of possession comprising of ${timestamp}.${fingerprint}.${format}:${signature}
	Nonce string `json:"nonce"`

	// Principals List of principals to include on the issued certificate
	Principals []string `json:"principals"`

	// PublicKey SSH public key to sign
	PublicKey string `json:"public_key"`
}

// PostHostCertificateRequestEndpointV2Params defines parameters for PostHostCertificateRequestEndpointV2.
type PostHostCertificateRequestEndpointV2Params struct {
	// Authorization Access Token JWT from OIDC IdP
	Authorization string `json:"Authorization"`
}

// PostHostCertificateRequestEndpointParams defines parameters for PostHostCertificateRequestEndpoint.
type PostHostCertificateRequestEndpointParams struct {
	// Authorization Access Token JWT from OIDC IdP
	Authorization string `json:"Authorization"`
}

// PostUserCertificateRequestEndpointParams defines parameters for PostUserCertificateRequestEndpoint.
type PostUserCertificateRequestEndpointParams struct {
	// Authorization Access Token JWT from OIDC IdP
	Authorization string `json:"Authorization"`
}

// GetRevocationListEndpointParamsCertificateType defines parameters for GetRevocationListEndpoint.
type GetRevocationListEndpointParamsCertificateType string

// PostRevokeCertificateEndpointParamsCertificateType defines parameters for PostRevokeCertificateEndpoint.
type PostRevokeCertificateEndpointParamsCertificateType string

// PostCertificateRequestEndpointV2JSONRequestBody defines body for PostCertificateRequestEndpointV2 for application/json ContentType.
type PostCertificateRequestEndpointV2JSONRequestBody PostCertificateRequestEndpointV2JSONBody

// PostHostCertificateRenewEndpointV2JSONRequestBody defines body for PostHostCertificateRenewEndpointV2 for application/json ContentType.
type PostHostCertificateRenewEndpointV2JSONRequestBody PostHostCertificateRenewEndpointV2JSONBody

// PostHostCertificateRequestEndpointV2JSONRequestBody defines body for PostHostCertificateRequestEndpointV2 for application/json ContentType.
type PostHostCertificateRequestEndpointV2JSONRequestBody PostHostCertificateRequestEndpointV2JSONBody

// PostHostCertificateRequestEndpointJSONRequestBody defines body for PostHostCertificateRequestEndpoint for application/json ContentType.
type PostHostCertificateRequestEndpointJSONRequestBody = HostCertificateRequest

// PostHostCertificateRenewEndpointJSONRequestBody defines body for PostHostCertificateRenewEndpoint for application/json ContentType.
type PostHostCertificateRenewEndpointJSONRequestBody = HostCertificateRenew

// PostUserCertificateRequestEndpointJSONRequestBody defines body for PostUserCertificateRequestEndpoint for application/json ContentType.
type PostUserCertificateRequestEndpointJSONRequestBody = UserCertificateRequest

// PostRevokeCertificateEndpointJSONRequestBody defines body for PostRevokeCertificateEndpoint for application/json ContentType.
type PostRevokeCertificateEndpointJSONRequestBody = CertificateRevocation
