name: ssh-ca-client
title: Serverless SSH CA Client
base: core24
adopt-info: version
summary: A client for a Serverless SSH CA
description: |
  This snap includes the graphical client-side component of a Serverless SSH CA
  that handles requesting and renewing user certificates for SSH access on your
  device.
  
  Also included is the CLI version, however the snap build does not include
  host SSH certificate management features.

  **Important:** This requires the deployment of the CA component on
  Cloudflare Workers, it does not work standalone.

  Please review the documentation here: https://github.com/andrewheberle/serverless-ssh-ca
contact: https://github.com/andrewheberle/serverless-ssh-ca/issues
source-code: https://github.com/andrewheberle/serverless-ssh-ca
issues: https://github.com/andrewheberle/serverless-ssh-ca/issues
website: https://github.com/andrewheberle/serverless-ssh-ca
license: Apache-2.0
icon: snap/gui/ssh-ca-client.png

grade: stable
confinement: strict

apps:
  ssh-ca-client:
    command: bin/ssh-ca-client
    plugs:
      - desktop
      - desktop-legacy
      - dot-agent
      - network
      - network-bind
      - password-manager-service
  cli:
    command: bin/ssh-ca-client-cli
    plugs:
      - desktop
      - dot-agent
      - network
      - network-bind
      - password-manager-service

parts:
  version:
    plugin: dump
    source: .
    source-type: local
    build-packages:
      - git
    override-pull: |
      craftctl default
      TAG="$(git describe --tags)"
      craftctl set version="${TAG#v}"
    stage:
      - -*

  scripts:
    plugin: dump
    source: client/scripts/utilities

  go-build:
    plugin: go
    source: ./client
    source-type: local
    build-snaps:
      - go/1.25/stable
    go-buildtags:
      - snap

platforms:
  amd64:

plugs:
  dot-agent:
    interface: personal-files
    write:
    - $HOME/.agent/ssh

