name: ssh-ca-client
base: core24
adopt-info: version
summary: A client for a Serverless SSH CA
description: |
  This snap includes the graphical client side component of a Serverless SSH CA
  that handles requesting and renewing user certificates on your device.
  
  Also included is the CLI version, however the snap version does not include
  host key management features.

grade: devel
confinement: devmode

apps:
  ssh-ca-client:
    command: bin/ssh-ca-client
  cli:
    command: bin/ssh-ca-client-cli

parts:
  version:
    plugin: dump
    source: .
    source-type: local
    build-packages:
      - git
    override-pull: |
      craftctl default
      TAG="$(git describe --tags)"
      craftctl set version="${TAG#v}"
    stage:
      - -*

  go-build:
    plugin: go
    source: ./client
    source-type: local
    build-snaps:
      - go/1.25/stable
    go-buildtags:
      - snap

platforms:
  amd64:

