import { parsePrivateKey, type PrivateKey } from "sshpk"

const caKey  = `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQTrh5Brsk2pEY/l1HUv9iB633qsuPzf
GxVbZUi7LXKitJua4v4mZEpuQfCGXa2ZYJtIIDXm+m3YdLkbAYBElWcSAAAAmJLgDFCS4A
xQAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOuHkGuyTakRj+XU
dS/2IHrfeqy4/N8bFVtlSLstcqK0m5ri/iZkSm5B8IZdrZlgm0ggNeb6bdh0uRsBgESVZx
IAAAAgenwTB1kprsmfs3e2PWGfZ4JDi+d5PTEMg6Rf3WgLZ+sAAAAA
-----END OPENSSH PRIVATE KEY-----
`

const userKey = `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQRjKUibbX9CLbTQlXNvE81xUdQ9Mbzt
56eu1c3gELG3WbJKw3GI0pcCehzw5k6V2lNJRGl/S+GIXP3An9THvRU5AAAAsFq3EABatx
AAAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGMpSJttf0IttNCV
c28TzXFR1D0xvO3np67VzeAQsbdZskrDcYjSlwJ6HPDmTpXaU0lEaX9L4Yhc/cCf1Me9FT
kAAAAhAIylYk8XpB+vvhmQRlWBc0ptx5C8p90ONWJyUU47gok+AAAAEHVzZXJAZXhhbXBs
ZS5jb20BAgMEBQYH
-----END OPENSSH PRIVATE KEY-----
`

const hostKey = `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQS5VBwIhM9+lrL71VrX+5MSaG31HTha
lwX3ZLX8Xvesiz+GRQQi5sSCgs29LK5EbpxO90TNZ26lXmouFQz0pPVkAAAAoJ5WQLOeVk
CzAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLlUHAiEz36WsvvV
Wtf7kxJobfUdOFqXBfdktfxe96yLP4ZFBCLmxIKCzb0srkRunE73RM1nbqVeai4VDPSk9W
QAAAAhANuVGDONB+pmASf7pjOLISf7nTFf4Sy2JJ2bIkLdcpFEAAAAAAECAwQFBgc=
-----END OPENSSH PRIVATE KEY-----
`

export const key = {
    ca(): PrivateKey {
        return parsePrivateKey(caKey)
    },
    host(): PrivateKey {
        return parsePrivateKey(hostKey)
    },
    user(): PrivateKey {
        return parsePrivateKey(userKey)
    },

}
