name: Build

on:
  pull_request:

permissions: {}

jobs:
  goreleaser-build:
    name: Build with GoReleaser
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: client/go.mod
          cache: false
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --snapshot
          workdir: client
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: client/dist/**/*.exe
          retention-days: 1
  msi-build:
    name: Package as an MSI
    runs-on: windows-latest
    needs: goreleaser-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: client/go.mod
          cache: false
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-artifact
          path: client/dist
      - name: Add WiX Toolset to path
        run: Write-Output $env:WIX | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install go-msi
        run: go install github.com/mh-cbon/go-msi@latest
      - name: Build MSI
        run: |
          cd client
          go-msi make --arch amd64 --out "$(Join-Path $([System.Environment]::CurrentDirectory) "tmp")" --src ".\templates" --msi ".\dist\ssh-ca-client.msi" --version "$(git describe --tags)"
          Write-Output "$((Get-FileHash -Algorithm SHA256 -Path ".\dist\ssh-ca-client.msi").Hash) ssh-ca-client.msi" | Out-File -FilePath ".\dist\ssh-ca-client.msi.sha256sum"
      - name: Upload MSI as artifact
        uses: actions/upload-artifact@v4
        with:
          name: msi-artifact
          path: client/dist/**/*.msi
          retention-days: 1
